theme: jekyll-theme-minimal
logo: assets/logo.png
title: Basics of hardware hacking
description: This course shows the basics of hardware hacking using password auhenticaton code as an example.<br/><br/>Created by <a href="https://twitter.com/maldr0id">@maldr0id</a>
